project_name: bloom-du

before:
  hooks:
    - go mod tidy

release:
  github:
    owner: capricornusx
    name: bloom-du
  name_template: '{{.Tag}}'
  prerelease: auto
  make_latest: true
  footer: |
    **Full Changelog**: https://github.com/capricornusx/bloom-du/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## What to do next?

    - Read the [Documentation](https://github.com/capricornusx/bloom-du)
  draft: false
builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "386"
      - goos: freebsd
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm64
    main: .

    ldflags: -s -w -X bloom-du/internal/build.Version={{.Version}}
    binary: bloom-du
    env:
      # https://github.com/goreleaser/goreleaser/issues/225
      - CGO_ENABLED=0
archives:
  - id: bloom-du
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    files:
      # - LICENSE*
      - README*
      - CHANGELOG*
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

dist: dist
signs:
  -
    cmd: gpg
    args:
      - --batch
      - -u
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - $signature
      - --clear-sign
      - --detach-sig
      - $artifact
    signature: ${artifact}.asc
    artifacts: checksum

  # .goreleaser.yaml
dockers:
  # You can have multiple Docker images.
  - #
    # ID of the image, needed if you want to filter by it later on (e.g. on custom publishers).
    id: bloom-du
    goos: linux
    goarch: amd64
    goamd64: "v1"

    # IDs to filter the binaries/packages.
    ids:
      - bloom-du

    # Templates of the Docker image names.
    # Templates: allowed
    image_templates:
      - "ghcr.io/capricornusx/bloom-du:{{ .Tag }}"
      - "ghcr.io/capricornusx/bloom-du:v{{ .Major }}"
      - "ghcr.io/capricornusx/bloom-du:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/capricornusx/bloom-du:latest"

    # Skips the docker push.
    # Could be useful if you also do draft releases.
    #
    # If set to auto, the release will not be pushed to the Docker repository
    #  in case there is an indicator of a prerelease in the tag, e.g. v1.0.0-rc1.
    #
    # Templates: allowed (since v1.19)
    skip_push: false

    # Path to the Dockerfile (from the project root).
    # Default: 'Dockerfile'
    # "{{ .Env.DOCKERFILE }}"
    dockerfile: Dockerfile

    # Set the "backend" for the Docker pipe.
    # Valid options are: docker, buildx, podman.
    # Podman is a GoReleaser Pro feature and is only available on Linux.
    # Default: 'docker'
    use: buildx

    # Docker build flags.
    # Templates: allowed
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      # - "--platform=linux/amd64/v3"

    # Extra flags to be passed down to the push command.
    push_flags:
      - --tls-verify=false

# TODO:
#nfpms:
#  - package_name: bloom-du
#    homepage: https://github.com/capricornusx/bloom-du
#    maintainer: Dmitry Dubinin <capricornusx@gmail.com>
#    description: |-
#      HTTP API for Bloom filter
#    formats:
#      - apk
#      - deb
#      - rpm
#      - archlinux