### Check value
GET http://localhost:8515/api/check?value=1234334
Accept: application/json
Content-Type: application/json

### Add value
POST http://localhost:8515/api/add?value=999111001x1
Accept: application/json
Content-Type: application/json


### Get Prometheus metrics
GET http://localhost:8515/metrics


### Check health
GET http://localhost:8515/health

