{
 "title": "bloom-du",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bloom_du_config_info,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Filter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Elements",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bloom_du_elements_total", "legendFormat": "elements added" }
   ]
  },
  {
   "title": "Filter config",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "bloom_du_config_info{instance=\"$instance\"}",
     "legendFormat": "p - (the number of cells decremented on every add)"
    }
   ]
  },
  {
   "title": "Rate requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(bloom_du_api_http_request_duration_seconds_count{instance=\"$instance\"}[5m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bloom_du_api_http_request_hist_duration_seconds_bucket{instance=\"$instance\", path=\"/api/check\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP Codes Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bloom_du_api_http_response_codes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Total Elements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bloom_du_elements_total{instance=\"$instance\"}",
     "legendFormat": "elements"
    }
   ]
  },
  { "title": "Golang", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "memstats_mspan_inuse_bytes"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "memstats_mspan_sys_bytes"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "memstats_mcache_inuse_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "memstats_mcache_sys_bytes"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "memstats_buck_hash_sys_bytes"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "memstats_gc_sys_bytes"
    },
    {
     "expr": "go_memstats_other_sys_bytes{instance=~\"$instance\"} - go_memstats_other_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations"
    },
    {
     "expr": "go_memstats_next_gc_bytes{instance=~\"$instance\"}",
     "legendFormat": "memstats_next_gc_bytes"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap_sys_bytes"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=~\"misc_mag.*\", instance=~\"$instance\"}",
     "legendFormat": "heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"misc_mag.*\", instance=~\"$instance\"}",
     "legendFormat": "heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=~\"misc_mag.*\", instance=~\"$instance\"}",
     "legendFormat": "heap_released_bytes"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "inuse"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "sys"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "sys_bytes"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=~\"$instance\"} - go_memstats_frees_total",
     "legendFormat": "Live objects"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "mallocs"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "alloc_bytes"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\", quantile=\"0.75\"}",
     "legendFormat": "gc_duration {{quantile}}"
    }
   ]
  }
 ]
}