name: lint-soft
on:
  push:
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    name: lint-soft
    runs-on: self-hosted
    strategy:
      matrix:
        go-version: [ 1.21.5 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: golangci-lint command line arguments.
          args: --config .golangci-soft.yml --issues-exit-code=0
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
